#include "../inc/FilterAutoGenerated.h"
#include <iostream>

void FilterAutoGenerated::apply(Image& img) {
    std::cout << "Applying " << type << " ...\n";
}

const std::string& FilterAutoGenerated::getType() const {
    return type;
}

int FilterAutoGenerated::getSize() const {
    return size;
}

void FilterAutoGenerated::setType(const std::string& newType) {
    type = newType;
}

void FilterAutoGenerated::setSize(int newSize) {
    size = newSize;
}
