#ifndef FILTERAUTOGENERATED_H
#define FILTERAUTOGENERATED_H

#include <string>
#include "Image.h"

class FilterAutoGenerated {
private:
    std::string type;
    int size;

public:
    void apply(Image& img);

    // getters
    const std::string& getType() const;
    int getSize() const;

    // setters
    void setType(const std::string& newType);
    void setSize(int newSize);
};

#endif
