#include "../inc/FilterAutoGenerated.h"
#include <iostream>

void FilterAutoGenerated::apply(Image& img) {
    if (type == "EdgeDetection") {
        std::cout << "Applying Edge Detection ...\n";
    } else if (type == "Blur") {
        std::cout << "Applying Blur ...\n";
    } else {
        std::cout << "Unknown filter type: " << type << "\n";
    }
}

const std::string& FilterAutoGenerated::getType() const {
    return type;
}

int FilterAutoGenerated::getSize() const {
    return size;
}

void FilterAutoGenerated::setType(const std::string& newType) {
    type = newType;
}

void FilterAutoGenerated::setSize(int newSize) {
    size = newSize;
}
