#include <iostream>
#include "../inc/Image.h"
#include "../inc/Filter.h"
#include "../inc/ImageProcessor.h"
#include "../inc/FilterAutoGenerated.h"
#include "../inc/FilterNoCopy.h"

std::string createSeparator(const std::string& text) {
    return "\n----- " + text + " -----\n\n";
}

int main() {
    std::cout << createSeparator("Create an image");
    Image img("image1.png");
    std::cout << "Image resolution: (" << img.getWidth() << "x" << img.getHeight() << ")\n";
    
    std::cout << createSeparator("Create filters");
    Filter edgeFilter("EdgeDetection", 1);
    Filter blurFilter("Blur", 2);
    Filter edgeFilter2("EdgeDetection", 3);
    
    std::cout << createSeparator("Create image processor");
    ImageProcessor processor;

    std::cout << createSeparator("Add filters to processor");
    processor.addFilter(edgeFilter);
    processor.addFilter(blurFilter);
    processor.addFilter(edgeFilter2);
    
    std::cout << createSeparator("Show processing pipeline");
    processor.showPipeline();

    std::cout << createSeparator("Apply the filters");
    processor.process(img);
    
    std::cout << createSeparator("Save the image");
    if (img.save("output.jpeg")) {
        std::cout << "Image saved successfully!\n";
    } else {
         std::cout << "Failed to save image!\n";
    }

    std::cout << createSeparator("Item5");
    Filter f1("Blur", 5); // constructor and destructor
    Filter f2(f1); // copy constructor
    f1 = f2; // copy assignment operator

    std::cout << createSeparator("Item5 - Part2");
    FilterAutoGenerated f3; // constructor and destructor
    f3.setType("Blur"); 
    f3.setSize(10);
    std::cout << "Filter " << f3.getType() << " and size " << f3.getSize() << "\n";

    FilterAutoGenerated f4(f3); // copy constructor
    std::cout << "Filter " << f4.getType() << " and size " << f4.getSize() << "\n";

    f4.setSize(100);
    f3 = f4; // copy assignment operator
    std::cout << "Filter " << f3.getType() << " and size " << f3.getSize() << "\n";

    std::cout << createSeparator("Item6");
    FilterNoCopy f5;
    f5.setType("Blur");
    f5.setSize(1000);
    std::cout << "Filter " << f3.getType() << " and size " << f3.getSize() << "\n";

    // FilterNoCopy f6(f5); // copy constructor

    // f5 = f6; // copy assignment operator


    // Copy constructor vs Move constructor
    std::cout << createSeparator("Copy constructor");
    ImageProcessor copied_processor = processor; // copy constructor

    std::cout << createSeparator("Move constructor");
    ImageProcessor moved_processor = std::move(processor); // move constructor

    std::cout << createSeparator("Destructors");

    return 0;

}

